# An example of a Kubernetes configuration for pod deployment.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # Cluster name.
  name: ignite-client
  namespace: ignite-namespace
spec:
  # The initial number of Ignite pods.
  replicas: 1
  serviceName: ignite-client
  selector:
    matchLabels:
      app: ignite-thick-client
  template:
    metadata:
      labels:
        app: ignite-thick-client
    spec:
      serviceAccountName: ignite
      # terminationGracePeriodSeconds: 60000 (use in production for graceful restarts and shutdowns)
      containers:
        # Custom pod name.
        - name: ignite-client-node
          image: ignite-thick-client
          imagePullPolicy: Never
          ports:
            - containerPort: 8088 # REST API
